server:
  port: 9090
  
  

spring:
  cloud:
    config:
      server:
       # git:
       #   uri: file:///${user.home}/Documents/properties/spring-cloud
        native:
          search-locations: file:///${user.home}/Documents/properties/spring-cloud/{application}/{profile}
          
          
  profiles:
    active: native
  application:
    name: config-server
    
    
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
          
          
          
          

